Repository CMU-313/spring24-nodebb-wildcats, pull requests merged in 2024-03, with the labels that each got.

#18 Automated Tests and Documentation for Instructor Only Announcements
  .github/workflows/hw1.yaml
  UserGuide.md
  public/openapi/components/schemas/CategoryObject.yaml
  public/openapi/read/admin/manage/admins-mods.yaml
  public/openapi/read/admin/manage/categories.yaml
  src/categories/create.js
  src/categories/data.js
  src/categories/search.js
  src/controllers/topics.js
  src/topics/create.js
  src/types/category.ts
  src/user/settings.js
  test/topics.js
  themes/nodebb-theme-persona/templates/account/settings.tpl
Labels: documentation, enhancement

#19 Anonymous Posting Implementation
  UserGuide.md
  plugins/nodebb-plugin-composer/.eslintrc
  plugins/nodebb-plugin-composer/.gitattributes
  plugins/nodebb-plugin-composer/.jshintrc
  plugins/nodebb-plugin-composer/LICENSE
  plugins/nodebb-plugin-composer/README.md
  plugins/nodebb-plugin-composer/controllers.js
  plugins/nodebb-plugin-composer/library.js
  plugins/nodebb-plugin-composer/package.json
  plugins/nodebb-plugin-composer/plugin.json
  plugins/nodebb-plugin-composer/screenshots/desktop.png
  plugins/nodebb-plugin-composer/screenshots/mobile.png
  plugins/nodebb-plugin-composer/static/less/composer.less
  plugins/nodebb-plugin-composer/static/less/medium.less
  plugins/nodebb-plugin-composer/static/less/page-compose.less
  plugins/nodebb-plugin-composer/static/less/textcomplete.less
  plugins/nodebb-plugin-composer/static/less/zen-mode.less
  plugins/nodebb-plugin-composer/static/lib/.eslintrc
  plugins/nodebb-plugin-composer/static/lib/admin.js
  plugins/nodebb-plugin-composer/static/lib/client.js
  plugins/nodebb-plugin-composer/static/lib/composer.js
  plugins/nodebb-plugin-composer/static/lib/composer/autocomplete.js
  plugins/nodebb-plugin-composer/static/lib/composer/categoryList.js
  plugins/nodebb-plugin-composer/static/lib/composer/controls.js
  plugins/nodebb-plugin-composer/static/lib/composer/drafts.js
  plugins/nodebb-plugin-composer/static/lib/composer/formatting.js
  plugins/nodebb-plugin-composer/static/lib/composer/preview.js
  plugins/nodebb-plugin-composer/static/lib/composer/resize.js
  plugins/nodebb-plugin-composer/static/lib/composer/scheduler.js
  plugins/nodebb-plugin-composer/static/lib/composer/tags.js
  plugins/nodebb-plugin-composer/static/lib/composer/uploads.js
  plugins/nodebb-plugin-composer/static/templates/admin/plugins/composer-default.tpl
  plugins/nodebb-plugin-composer/static/templates/compose.tpl
  plugins/nodebb-plugin-composer/static/templates/composer.tpl
  plugins/nodebb-plugin-composer/static/templates/modals/topic-scheduler.tpl
  plugins/nodebb-plugin-composer/websockets.js
  public/openapi/read/post/pid.yaml
  public/openapi/write/posts/pid.yaml
  public/src/client/topic/posts.js
  src/api/topics.js
  src/controllers/composer.js
  src/controllers/composer.ts
  src/controllers/composer_original.js
  src/controllers/write/topics.js
  src/posts/create.js
  src/posts/data.js
  src/topics/create.js
  src/types/post.ts
  test/api.js
  test/controllers.js
Labels: enhancement

#20 Automated Tests and Documentation for Anonymous Post
  UserGuide.md
  plugins/nodebb-plugin-composer/library.js
  test/controllers.js
  test/posts.js
Labels: documentation, enhancement

#22 Add instructor only translation to all files
  public/language/ar/error.json
  public/language/bg/error.json
  public/language/bn/error.json
  public/language/cs/error.json
  public/language/da/error.json
  public/language/de/error.json
  public/language/el/error.json
  public/language/en-x-pirate/error.json
  public/language/es/error.json
  public/language/et/error.json
  public/language/fa-IR/error.json
  public/language/fi/error.json
  public/language/fr/error.json
  public/language/gl/error.json
  public/language/he/error.json
  public/language/hr/error.json
  public/language/hu/error.json
  public/language/hy/error.json
  public/language/id/error.json
  public/language/it/error.json
  public/language/ja/error.json
  public/language/ko/error.json
  public/language/lt/error.json
  public/language/lv/error.json
  public/language/ms/error.json
  public/language/nb/error.json
  public/language/nl/error.json
  public/language/pl/error.json
  public/language/pt-BR/error.json
  public/language/pt-PT/error.json
  public/language/ro/error.json
  public/language/ru/error.json
  public/language/rw/error.json
  public/language/sk/error.json
  public/language/sl/error.json
  public/language/sq-AL/error.json
  public/language/sr/error.json
  public/language/sv/error.json
  public/language/th/error.json
  public/language/tr/error.json
  public/language/uk/error.json
  public/language/vi/error.json
  public/language/zh-CN/error.json
  public/language/zh-TW/error.json
Labels: bug
